ecomlikeside/urls.py
from django.contrib import admin
from django.urls import path,include
import datetime as dt

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("sellspage.urls")),
    
]

sellspage/urls.py
from django.urls import path
from . import views

app_name = "sellspage"

urlpatterns = [
    # path('', views.self_profile, name='self_profile'),
    path('', views.self_profile, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),

    path('profile/', views.self_profile, name='self_profile_'),
    path('profile/edit/', views.profile_edit_view, name='profile_edit'),
    path('profile/<str:username>/', views.profile_view, name='profile'),

    path('listings', views.listings_view, name='listings'),
    path('listing/add/', views.add_listing_product_view, name='add_listing_product'),
    path('listing/<int:id>/', views.listing_detail_view, name='listing_detail'), # todo : imp
    path('listing/<int:id>/', views.listing_detail_view, name='product_detail'), # todo : imp
    path('listing/<int:id>/edit/', views.edit_listing_view, name='edit_listing'),
    path('listing/<int:id>/delete/', views.delete_listing_view, name='delete_listing'),
    # todo path('listing/<int:id>/order/', views.order_view, name='place_order'),
    # todo path('listing/<int:id>/wishlist/', views.wishlist_view, name='wishlist'),

    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('order/', views.order_view, name='order'),
    

    path('comment/add/<int:product_id>/', views.add_comment_view, name='add_comment'),
    path('comment/delete/<int:comment_id>/', views.delete_comment_view, name='delete_comment'),
]

sellspage/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
from .models import SellsPageUser, Product, Contracts, Order, Comment, Wishlist

from .utils import choiceListGen, productTypes


class UserRegistrationForm(UserCreationForm):
	email = forms.EmailField(
		required=True, widget=forms.EmailInput(attrs={"placeholder": "Email Address"})
	)
	first_name = forms.CharField(
		max_length=50,
		required=True,
		widget=forms.TextInput(attrs={"placeholder": "First Name"}),
	)
	last_name = forms.CharField(
		max_length=50,
		required=True,
		widget=forms.TextInput(attrs={"placeholder": "Last Name"}),
	)
	date_of_birth = forms.DateField(
		required=False, widget=forms.DateInput(attrs={"type": "date"})
	)
	bio = forms.CharField(
		required=False,
		widget=forms.Textarea(attrs={"placeholder": "Bio"}),
	)

	class Meta:
		model = SellsPageUser
		fields = [
			"username",
			"first_name",
			"last_name",
			"bio",
			"email",
			"date_of_birth",
			"password1",
			"password2",
		]

	def clean_email(self):
		email = self.cleaned_data.get("email")
		if SellsPageUser.objects.filter(email=email).exists():
			raise ValidationError(_("A user with that email already exists."))
		return email


class UserProfileEditForm(forms.ModelForm):
	email = forms.EmailField(
		required=True, widget=forms.EmailInput(attrs={"placeholder": "Email Address"})
	)
	first_name = forms.CharField(
		max_length=50,
		required=True,
		widget=forms.TextInput(attrs={"placeholder": "First Name"}),
	)
	last_name = forms.CharField(
		max_length=50,
		required=True,
		widget=forms.TextInput(attrs={"placeholder": "Last Name"}),
	)
	date_of_birth = forms.DateField(
		required=False, widget=forms.DateInput(attrs={"type": "date"})
	)
	bio = forms.CharField(
		required=False,
		widget=forms.Textarea(attrs={"placeholder": "Bio"}),
	)

	class Meta:
		model = SellsPageUser
		fields = [
			"username",
			"first_name",
			"last_name",
			# todo "location",
			"bio",
			"email",
			"date_of_birth",
		]


	def clean_username(self):
		username = self.cleaned_data.get("username")
		if (
			SellsPageUser.objects
			.exclude(pk=self.instance.pk)
			.filter(username=username)
			.exists()
		):
			raise ValidationError(_("A user with that username already exists."))
		return username
 
	def clean_email(self):
		print(dir(self.instance.username))
		email = self.cleaned_data.get("email")
		username = self.cleaned_data.get("username")
		if (
			SellsPageUser.objects
			.exclude(pk=self.instance.pk)
			.filter(email=email)
			.exists()
		):
			raise ValidationError(_("A user with that email already exists."))
		return email


class UserLoginForm(AuthenticationForm):
	username = forms.CharField(
		max_length=254,
		widget=forms.TextInput(attrs={"autofocus": True}),
	)
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
	)

	def clean_username(self):
		username = self.cleaned_data.get("username")
		if not username:
			raise ValidationError("Username is required.")
		return username

	def clean_password(self):
		password = self.cleaned_data.get("password")
		if not password:
			raise ValidationError("Password is required.")
		return password

	def confirm_login_allowed(self, user):
		if not user.is_active:
			raise ValidationError("This account is inactive.")
		# Add any other custom checks here if needed


class ProductForm(forms.ModelForm):
	price = forms.FloatField(
		validators=[MinValueValidator(0.01)],
		widget=forms.NumberInput(attrs={"placeholder": "Price"}),
	)
	title = forms.CharField(
		max_length=50,
		required=True,
		widget=forms.TextInput(attrs={"placeholder": "Title"}),
	)
	description = forms.CharField(
		max_length=750,
		required=False,
		widget=forms.Textarea(attrs={"placeholder": "Short Description"}),
	)
	long_description = forms.CharField(
		max_length=1500,
		required=False,
		widget=forms.Textarea(attrs={"placeholder": "Long Description"}),
	)
	# print(Product._meta.get_field('product_type').choices) # This works
	product_type = forms.ChoiceField(
		choices=Product._meta.get_field("product_type").choices, required=True
	)
	# product_type = forms.ChoiceField(choices=choiceListGen(productTypes), required=True)

	class Meta:
		model = Product
		fields = [
			"title",
			"main_image",
			"price",
			"description",
			"long_description",
			"product_type",
		]


class ContractsForm(forms.ModelForm):
	whatsapp_phone = forms.CharField(
		max_length=20,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "Whatsapp Phone"}),
	)
	whatsapp_link = forms.URLField(
		max_length=200,
		required=False,
		widget=forms.URLInput(attrs={"placeholder": "Whatsapp Link"}),
	)
	imo_phone = forms.CharField(
		max_length=20,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "IMO Phone"}),
	)
	phone = forms.CharField(
		max_length=20,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "Personal Phone"}),
	)
	bkash_phone = forms.CharField(
		max_length=20,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "Bkash Phone"}),
	)
	nagad_phone = forms.CharField(
		max_length=20,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "Nagad Phone"}),
	)
	facebook_username = forms.CharField(
		max_length=50,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "Facebook Username"}),
	)
	messenger_username = forms.CharField(
		max_length=50,
		required=False,
		widget=forms.TextInput(attrs={"placeholder": "Messenger Username"}),
	)
	facebook_link = forms.URLField(
		max_length=200,
		required=False,
		widget=forms.URLInput(attrs={"placeholder": "Facebook Link"}),
	)
	messenger_link = forms.URLField(
		max_length=200,
		required=False,
		widget=forms.URLInput(attrs={"placeholder": "Messenger Link"}),
	)

	class Meta:
		model = Contracts
		fields = [
			"whatsapp_phone",
			"whatsapp_link",
			"imo_phone",
			"phone",
			"bkash_phone",
			"nagad_phone",
			"facebook_username",
			"messenger_username",
			"facebook_link",
			"messenger_link",
		]


class OrderForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ["product"]

	def __init__(self, *args, **kwargs):
		user = kwargs.pop("user", None)
		super().__init__(*args, **kwargs)
		if user:
			self.fields["product"].queryset = user.listed_products.filter(
				is_available=True
			)


class CommentForm(forms.ModelForm):
	comment = forms.CharField(
		widget=forms.Textarea(attrs={"placeholder": "Add your comment here..."}),
		max_length=500,
		required=True,
	)

	class Meta:
		model = Comment
		fields = ["comment"]


class WishlistForm(forms.ModelForm):
	class Meta:
		model = Wishlist
		fields = ["product"]

	def __init__(self, *args, **kwargs):
		user = kwargs.pop("user", None)
		super().__init__(*args, **kwargs)
		if user:
			self.fields["product"].queryset = Product.objects.exclude(
				wishlists__user=user
			)

sellspage/views.py
# sellspage/views.py

from django.shortcuts import render, redirect, get_object_or_404

# from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from .forms import UserRegistrationForm, ProductForm, UserLoginForm, UserProfileEditForm
from .models import SellsPageUser, Product, Order, Comment, Wishlist, PhotoModel
from .utils import filter_dict


def login_required(view_func):
    """Custom decorator to check if the user is logged in."""
    def _wrapped_view(request, *args, **kwargs):
        if request.user.is_authenticated:
            return view_func(request, *args, **kwargs)
        else:
            # Redirect to the login page if not authenticated
            return redirect(reverse('salespage:login'))  # Change 'login' to your login URL name
    return _wrapped_view


def listings_view(request, pageNo=None):
    all_listings = Product.objects.all().order_by('-id')
    paginator = Paginator(all_listings, 10)  # Show 10 listings per page
    page_number = pageNo or request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    return render(request, 'sellspage/listings.html', {'page_obj': page_obj})


@login_required
# def profile_edit_view(request, username):
def profile_edit_view(request):
    print(request.user)
    user = get_object_or_404(SellsPageUser, username=request.user.username)
    if request.method == "POST":
        # form = UserRegistrationForm(request.POST, instance=user)
        form = UserProfileEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect("sellspage:profile", username=user.username)
    else:
        form = UserProfileEditForm(instance=user)
    # todo : make a profile edit templete
    return render(request, "sellspage/profile_edit.html", {"form": form, "user": user})


def listing_detail_view(request, id):
    # print(id)
    product = get_object_or_404(Product, id=id)
    user = request.user if request.user.is_authenticated else None
    liked = user and product.likes.filter(id=user.id).exists()

    context = {
        "product": product,
        "liked": liked,
        "profile_type": "Seller" if product.listed_by.is_seller else "Customer",
    }

    return render(request, "sellspage/product.html", context)
    return render(request, "sellspage/listing_detail.html", context)

def home(request):
    return redirect("sellspage:self_profile")

def self_profile(request):
    if request.user is None or not request.user.is_authenticated:
        return redirect("sellspage:login")
    return redirect("sellspage:profile", username=request.user.username)


@login_required
def add_listing_product_view(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            user = get_object_or_404(SellsPageUser, username = request.user.username)
            product.listed_by = user
            product.save()
            messages.success(request, "Product added successfully.")
            return redirect(reverse("sellspage:profile", args=[request.user.username]))
            # return redirect(product.get_absolute_url())
    else:
        form = ProductForm()
        # print(str(form["product_type"]))
        # print(form,form.product_type.field.queryset)
    return render(request, "sellspage/addListingProduct.html", {"form": form})


@login_required
def edit_listing_view(request, id):
    product = get_object_or_404(Product, id=id, listed_by=request.user)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Product updated successfully.")
            return redirect(product.get_absolute_url())
    else:
        form = ProductForm(instance=product)
    return render(
        request, "sellspage/edit_listing.html", {"form": form, "product": product}
    )


@login_required
def delete_listing_view(request, id):
    product = get_object_or_404(Product, id=id, listed_by=request.user)
    if request.method == "POST":
        product.delete()
        messages.success(request, "Product deleted successfully.")
        return redirect("sellspage:profile", username=request.user.username)
    return render(request, "sellspage/delete_listing.html", {"product": product})


@login_required
def wishlist_view(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    return render(
        request, "sellspage/wishlist.html", {"wishlist_items": wishlist_items}
    )


@login_required
def order_view(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, "sellspage/order.html", {"orders": orders})


@login_required
def add_comment_view(request, product_id):
    user: SellsPageUser = get_object_or_404(SellsPageUser, pk=request.user.pk)
    product: Product = get_object_or_404(Product, id=product_id)
    if request.method == "POST":
        comment_text = request.POST.get("comment")
        if comment_text:
            Comment.objects.create(
                product=product, user=user, comment=comment_text
            )
            messages.success(request, "Comment added successfully.")
        else:
            messages.error(request, "Comment cannot be empty.")
    return redirect(product.get_absolute_url())


@login_required
def delete_comment_view(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    if request.method == "POST":
        comment.delete()
        messages.success(request, "Comment deleted successfully.")
    return redirect("sellspage:profile", username=request.user.username)


def login_view(request):
    if request.method == "POST":
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Login successful.")
                return redirect("sellspage:profile", username=user.username)
            else:
                messages.error(request, "Invalid credentials.")
    else:
        form = UserLoginForm()
    return render(request, "sellspage/login.html", {"form": form})


def logout_view(request):
    logout(request)
    messages.success(request, "Logged out successfully.")
    return redirect("sellspage:login")


def register_view(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Registration successful.")
            return redirect("sellspage:login")
    else:
        form = UserRegistrationForm()
    return render(request, "sellspage/register.html", {"form": form})


def profile_view(request, username) -> HttpResponse:
    user = get_object_or_404(SellsPageUser, username=username)
    context = {
        "isThisPageUser": user.username == request.user.username,
        "user": user,
        "page_data": user.get_page(page_no=request.GET.get("page", 1)),
    }
    return render(request, "sellspage/profile.html", context)

sellspage/templates/sellspage/listings.html
<!-- templates/sellspage/listings.html -->
{% extends 'sellspage/layout.html' %}

{% block main %}
<h1>All Listings</h1>

<div class="listings">
    {% for product in page_obj %}
        <div class="listing-item">
            <h2>{{ product.title }}</h2>
            <p>Price: ${{ product.price }}</p>
            <p>Posted by: {{ product.listed_by.username }}</p>
            <p><a href="{% url 'sellspage:listing_detail' product.id %}">View Details</a></p>
        </div>
    {% empty %}
        <p>No listings available at the moment.</p>
    {% endfor %}
</div>

<!-- Pagination controls -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

sellspage/templates/sellspage/navbar.html
<!-- templates/sellspage/navbar.html -->
<nav>
  <ul>
    <li><a href="{% url 'sellspage:home' %}">Home</a></li>
    <li><a href="{% url 'sellspage:listings' %}">Products</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'sellspage:add_listing_product' %}">Add product</a></li>
    <li><a href="{% url 'sellspage:wishlist' %}">Wishlist</a></li>
    <li><a href="{% url 'sellspage:order' %}">Cart</a></li>
    <li><a href="{% url 'sellspage:profile' user.username %}">Profile</a></li>
    <li><a href="{% url 'sellspage:logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'sellspage:register' %}">Register</a></li>
    <li><a href="{% url 'sellspage:login' %}">Login</a></li>
    {% endif %}
  </ul>
</nav>

sellspage/templates/sellspage/old_one_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Social Network{% endblock %}</title>
    {% comment %} <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link href="{% static 'sellspage/network/styles.css' %}" rel="stylesheet" />
    <style>
        .authOnly{
            display : {% if  user.is_authenticated %}hi{% else %}none !important{% endif %};
        }
    </style>
    <script>

        var CU = {
          0 : {% if user.is_authenticated %}true{% else %}false{% endif %},
          "username" : '{% if user.is_authenticated %}{{user.username}}{% else %}Anonymous{% endif %}',
          "is_active" : {% if user.is_active %}true{% else %}false{% endif %},
          "is_staff" : {% if user.is_staff %}true{% else %}false{% endif %},
          "is_anonymous" : {% if user.is_anonymous %}true{% else %}false{% endif %},
          "is_superuser" : {% if user.is_superuser %}true{% else %}false{% endif %},
          "is_authenticated" : {% if user.is_authenticated %}true{% else %}false{% endif %}
      }
    </script> {% endcomment %}
  </head>
  <body>
    {% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Network</a>

      <div>
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a
              class="nav-link user CU"
              onclick="loadViewPage('user/{{ user.username }}')"
              href="#"
              ><strong>{{ user.username }}</strong></a
            >
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" onclick="loadViewPage('posts')" {% comment %} href="{% url 'sellspage:index' %}" {% endcomment %}>All Posts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" onclick="loadViewPage('followingPosts')">Following</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" onclick="loadViewPage('edit','')" {% comment %} href="?url=edit" {% endcomment %}>Add New Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sellspage:logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sellspage:login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sellspage:register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav> {% endcomment %}

    <div class="body">{% block body %}{% endblock %}</div>
    {% block script %}{% endblock %}
  </body>
</html>

sellspage/templates/sellspage/product.html
{% extends 'sellspage/layout.html' %}

{% block title %}Product {{ product.title }}{% endblock %}

{% block extra_head %}
<!-- Add any specific head elements for this page if needed -->
{% endblock %}

{% block main %}
<div class="product-page">
    <img class="product-image" src="{{ product.main_image.get_url }}" alt="{{ product.title }} product image">
    
    <div class="product-details">
        <h1 class="product-title">{{ product.title }}</h1>
        <div class="availability {% if product.is_available %}available{% else %}unavailable{% endif %}">
            {% if product.is_available %}
                Available
            {% else %}
                Sold Out
            {% endif %}
        </div>
        <div class="posted-on">Posted On: {{ product.posted_on|date:"F j, Y" }}</div>
        
        {% if product.is_available %}
        <div class="stock">Only {{ product.stock }} left in stock</div>
        {% endif %}
        
        <div class="description">
            <h2>Description</h2>
            <p>{{ product.description }}</p>
        </div>
        <div class="description">
            <h2>Details about products</h2>
            <p>{{ product.long_description }}</p>
        </div>
        <div class="price">
            <span class="bold">Price: </span>${{ product.price }}
        </div>
        <div class="wishlisted-by">
            <span class="bold">Wishlisted by: </span>{{ product.wishlist_count }} people
        </div>
        <div class="sold-to">
            <span class="bold">Sold to: </span>{{ product.sold_count }} people
        </div>
        
        <div class="actions">
            {% if user.is_authenticated %}
            {% comment %} todo <form action="{% url 'sellspage:add_to_cart' product.id %}" method="post" class="add-to-cart-form">
                {% csrf_token %}
                <button type="submit" class="btn">Add to Cart</button>
            </form>
            <form action="{% url 'sellspage:place_order' product.id %}" method="post" class="order-form">
                {% csrf_token %}
                <button type="submit" class="btn">Order Now</button>
            </form> {% endcomment %}
            {% else %}
            <p>Please <a href="{% url 'sellspage:login' %}">log in</a> to purchase this product.</p>
            {% endif %}
        </div>
    </div>

    <div class="product-gallery">
        <h2>Product Images</h2>
        <div class="images">
            {% for image in product.images.all %}
            <img src="{{ image.url }}" alt="{{ product.title }} image">
            {% empty %}
            <p>No additional images available.</p>
            {% endfor %}
        </div>
    </div>

    <div class="comments">
        <h2>Comments</h2>
        <form action="{% url 'sellspage:add_comment' product.id %}" method="post" class="comment-form">
            {% csrf_token %}
            <input type="text" name="comment" placeholder="Add a comment" required>
            <button type="submit" class="btn">Submit</button>
        </form>
        <ul class="comments">
            {% for comment in product.comments_default %}
            <li class="comment">
                <strong>{{ comment.user__username }}:</strong> {{ comment.comment }} <sup>{{comment.timestamp}}</sup>
            </li>
            {% empty %}
            
            <li>No comments yet.</li>
            {% endfor %}
        </ul>
    </div>
    
    <div class="related-products">
        <h2>Related Products</h2>
        <div class="product-list">
            {% for related_product in related_products %}
            <div class="product" data-product-id="{{ related_product.id }}">
                <a href="{% url 'sellspage:product_detail' related_product.id %}">
                    <img src="{{ product.main_image.get_url }}" alt="{{ related_product.title }}">
                    <div class="p-info">
                        <div class="title">{{ related_product.title }}</div>
                        <div class="price">${{ related_product.price }}</div>
                        <div class="bought-by">{{ related_product.bought_by_count }} people</div>
                    </div>
                </a>
            </div>
            {% empty %}
            <p>No related products available.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block extra_script %}
<!-- Add any specific scripts for this page if needed -->
{% endblock %}

sellspage/templates/sellspage/profile.html
{% extends "sellspage/layout.html" %} 
{% load static %}   


{% block title %}Profile{% endblock title %} 
{% block main %}
<div id="main" class="main" page="profile">
  <div class="profileData">
    <img
      class="shadow cover"
      src="{% static 'sellspage/images/cover.png' %}"
      alt="cover photo"
      width="100%"
    />
    <div class="infos">
      <img
        class="profile shadow"
        src="{% static 'sellspage/images/profile.png' %}"
        alt="profile"
      />
      <div class="infos">
        <div class="name">{{ user.full_name }}</div>

        <div class="title">{{ user.title }}</div>
        <hr />
        <div class="phone">{{ user.phone }}</div>
        <div class="location">{{ user.location }}</div>
        <hr />
        <div class="bio">{{ user.bio }}</div>
      </div>
      <hr />
    </div>
    <hr />
    {% if isThisPageUser %}
    <div class="edit_btn">
      <a href="{% url 'sellspage:profile_edit' %}"> Edit your profile </a>
    </div>
    {% endif %}
    <div class="contracts">
      <a
      href="https://wa.me/{{ user.whatsapp }}"
      data-iconof="Whatsapp"
      class="whatsapp icon"
      target="_blank"
      ><span class="name" data-iconof="Whatsapp"></span
        ></a>
        <a
        href="{{ user.imo_link }}"
        data-iconof="Imo"
        class="imo icon whatsapp"
        target="_blank"
        ><span class="name" data-iconof="Imo"></span
      ></a>
      <a
        href="https://m.me/{{ user.messenger }}"
        data-iconof="Messenger"
        class="messenger icon message"
        target="_blank"
        ><span class="name" data-iconof="Messenger"></span
      ></a>
      <a
        href="https://facebook.com/{{ user.facebook }}"
        data-iconof="Facebook"
        class="facebook icon"
        target="_blank"
        ><span class="name" data-iconof="Facebook"></span
      ></a>
      <a
        href="tel:{{ user.phone }}"
        data-iconof="Phone"
        class="phone icon"
        target="_blank"
        ><span class="name" data-iconof="Phone"></span
      ></a>
      <a
        href="mailto:{{ user.email }}"
        data-iconof="Email"
        class="email icon"
        target="_blank"
        ><span class="name" data-iconof="Email"></span
      ></a>
    </div>
    <hr />
  </div>

  <div class="products">
    todo canbe used on produts =>{% for item in user.get_page%}{{item}}, {% endfor %}
    <h2 class="heading">Products</h2>
    {% if isThisPageUser %}
    <div class="Addprodut">
      <a href="{% url 'sellspage:add_listing_product' %}"> Add product </a>
    </div>
    {% endif %}

    {% for product in user.get_page.products%}
    <div
      class="product"
      data-product-id="{{ product.id }}"
      onclick="window.location.replace('{% url 'sellspage:product_detail' product.id %}')"
    >
      <div class="product-image">
        <img
          src="{{ product.image.url }}"
          alt="{{ product.title }} product image"
        />
      </div>
      <div class="p-infos product-container" >
        <div class="title">{{ product.title }}</div>
        <div class="price">${{ product.price }}</div>
        <div class="broghtby">{{ product.bought_by_count }} people</div>
      </div>
    </div>
    {% empty %}
    <div>No product.</div>
    {% endfor %}
  </div>
  {% endblock main %}
</div>

sellspage/templates/sellspage/profile_edit.html
<!-- templates/sellspage/profile_edit.html -->
{% extends "sellspage/layout.html" %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
</form>
{% endblock %}